version: '3.5'

services:
  api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/api
    environment:
      HOST: "${HOST}" 
      PORT: "${PORT}" 
      CONSUMER_KEY: "${}"
      CONSUMER_SECRET: "${}"
      ACCESS_TOKEN: "${}"
      ACCESS_TOKEN_SECRET: "${}"
      FLASK_ENV: "${FLASK_ENV}" 
      MONGO_URL: "${MONGO_URL}"
    depends_on:
      - mongo
  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/db/data
